substitutions:
  device_name: office-light
  friendly_name: Office Light
  assigned_ip_address: "192.168.86.207"

packages:
  dimmer_light: !include common/dimmer_light.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
